services:
  crud-webapi:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
        - "8080:8080"
    container_name: patient_management
    depends_on:
        - db
  db: 
    image: postgres:latest
    ports: 
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: PatientManagement
    container_name: db_postgres_container